//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfThing
    {
        public int ListOfThing_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Sum { get; set; }
        public Nullable<int> FKThingID { get; set; }
        public Nullable<int> FKConditionID { get; set; }
        public Nullable<int> FKUnitID { get; set; }
        public Nullable<int> FKUserID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Thing Thing { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual User User { get; set; }
    }
}
