//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ListOfThing = new HashSet<ListOfThing>();
        }
    
        public int User_ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> FKRoleID { get; set; }
        public Nullable<int> FKEnterpriseID { get; set; }
        public byte[] ImageUsers { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfThing> ListOfThing { get; set; }
        public virtual Role Role { get; set; }

        public string FullName
        {
            get => $"{LastName} {FirstName.Substring(0, 1)}. {MiddleName.Substring(0, 1)}.";
        }
    }
}
